version: "3.9"
services:
  web:
    # The `web` service uses an image that’s built from the Dockerfile in the current directory.
    build: .
    image: lts-admin-tomcat:1.7.0
    container_name: lts-admin-1.7.0-tomcat
    # restart: always

    # It then binds the container and the host machine to the exposed port, `5000`.
    # This example service uses the default port for the Flask web server, `5000`.
    ports:
      - "8080:8080"
      - "8730:8730"
    # The new `volumes` key mounts the project directory (current directory) on the host to `/code` inside the container,
    volumes:
      - "./config/lts-admin.cfg:/usr/local/tomcat/webapps/lts-admin/WEB-INF/classes/lts-admin.cfg"
      - "./config/lts-monitor.cfg:/usr/local/tomcat/webapps/lts-admin/WEB-INF/classes/lts-monitor.cfg"
    environment:
       APPLICATION_NAME: lts-admin-docker-compose
       # TODO 2021-10-14，`lts-admin.cfg` 和 `lts.monitor.cfg` 中无法通过环境变量指定 zk/mysql 地址等。